name: "Check Folders for changes in last commit"
description: "Checks if the last commit contains changes in specified folders"
inputs:
  folders:
    description: "Comma-separated list of folders to check"
    required: true
outputs:
  changes_detected:
    description: "Indicates whether changes were detected"
runs:
  using: "composite"
  steps:
    - name: Check changes
      run: |
        FOLDERS_TO_CHECK=(${{ inputs.folders }})
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
        for folder in "${FOLDERS_TO_CHECK[@]}"; do
          if echo "$CHANGED_FILES" | grep -q "^$folder/"; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done
        echo "changes_detected=false" >> "$GITHUB_OUTPUT"
      shell: bash

